const dicas = [
"Dica: Evite usar gírias em textos formais.",
"Dica: Sempre utilize a vírgula antes da conjunção 'e' quando há mais de dois elementos.",
"Dica: Use 'a' antes de palavras femininas e 'o' antes de palavras masculinas.",	"Dica: O correto é 'mais' quando se refere a quantidade e 'mas' quando se opõe a algo.",
"Dica: Sempre coloque acento no 'é' (verbo ser) e no 'é' (verbo estar) para diferenciar ações permanentes de ações momentâneas.",
"Dica: Use o hífen para unir as palavras compostas (como 'pé-de-moleque', 'guarda-chuva', etc).",
"Dica: Evite usar palavras vulgares ou de baixo calão em textos formais.",
"Dica: Utilize a crase antes de substantivos femininos que indicam lugar (como 'à escola', 'à igreja', etc).",
"Dica: Utilize o ponto final para encerrar frases declarativas e o ponto de interrogação para fazer perguntas.",
"Dica: Utilize a vírgula para separar elementos em uma enumeração, mas nunca antes da conjunção 'e'.",
"Dica: Evite o uso excessivo de pronomes em uma frase, especialmente quando eles se referem a objetos ou coisas inanimadas.",
"Dica: Utilize o ponto e vírgula para separar frases independentes que estejam relacionadas entre si.",
"Dica: Utilize a linguagem coloquial apenas em contextos informais e evite seu uso em textos formais.",
"Dica: Utilize acentos diferenciais em palavras como 'pôr' e 'pôde' para diferenciá-las de outras palavras homófonas.", 
"Dica: Evite o uso de palavras repetitivas em um mesmo parágrafo, para não tornar o texto monótono e cansativo.",
"Dica: Utilize o ponto de exclamação com moderação, pois seu uso excessivo pode tornar o texto pouco crível e exagerado.",
"Dica: Utilize corretamente os pronomes relativos 'que' e 'quem', para não comprometer a clareza e a compreensão da frase.",
"Dica: Utilize o apóstrofo para indicar a supressão de letras em palavras contraídas, como em 'd'água' e 'não sei'.",
"Dica: Evite o uso de termos técnicos ou jargões em textos destinados a um público geral, a menos que estejam bem explicados no contexto.", 
"Dica: Utilize o acento agudo nas vogais tônicas 'a', 'e' e 'o' das palavras oxítonas, como em 'café', 'bebê' e 'avô'",
"Dica: Utilize o acento circunflexo nas vogais tônicas 'a', 'e' e 'o' das palavras paroxítonas, como em 'pêssego', 'carência' e 'cômodo'",
"Dica: Utilize o acento grave para indicar a crase, que é a contração da preposição 'a' com o artigo feminino 'a', como em 'à casa' e 'à escola'",
"Dica: Utilize o trema para indicar a pronúncia correta de vogais que formam um hiato, como em 'linguiça'",
"Dica: Utilize o acento diferencial em palavras homógrafas para diferenciá-las, como em 'pôde' (pretérito perfeito do verbo poder) e 'pode' (presente do indicativo do verbo poder)'",
"Dica: Utilize 'onde' quando se refere a lugar físico e 'em que' quando se refere a lugar abstrato.",
"Dica: As palavras proparoxítonas sempre são acentuadas, como em 'sábado', 'próximo' e 'próton'.",
"Dica: As palavras terminadas em ditongo crescente (ou seja, quando a vogal mais fraca vem primeiro) são acentuadas, como em 'saúde', 'chapéu' e 'herói'.",
"Dica: As palavras terminadas em 'em', 'ens' e 'on' são acentuadas na sílaba tônica, como em 'parabéns', 'hífen' e 'órgão'.",
"Dica: As palavras terminadas em 'ã', 'ãs', 'ão' e 'ões' são acentuadas, como em 'amanhã', 'irmãs', 'coração' e 'nações'.",
"Dica: Utilize sempre letras maiúsculas no início de frases, nomes próprios e em siglas, como em 'Brasil', 'UNESCO' e 'João'.",
"Dica: O uso da crase é obrigatório antes de palavras femininas que exigem a preposição 'a' e que podem ser substituídas por 'àquela', como em 'fui à escola', 'à espera de um milagre' e 'à moda antiga'.",
"Dica: O uso do hífen é obrigatório em palavras compostas com prefixos 'ex', 'vice', 'pró', 'pós' e 'pré', como em 'ex-presidente', 'vice-diretor', 'pró-reitor', 'pós-graduação' e 'pré-história'.",
"Dica: Utilize o ponto final para marcar o final de uma frase declarativa, o ponto de exclamação para marcar uma emoção intensa e o ponto de interrogação para marcar uma pergunta.",
"Dica: Ao utilizar siglas, escreva todas as letras em maiúsculo, como em 'ONG', 'ABNT' e 'IBGE'.",
"Dica: Utilize o ponto de exclamação para finalizar frases declarativas e imperativas, como em 'Faça sua inscrição agora!'.",
"Dica: Utilize o ponto de interrogação para indicar perguntas diretas, como em 'Qual é o seu nome?' e 'Você já fez a tarefa?'.",
"Dica: Utilize o ponto e vírgula para separar ideias independentes dentro de um mesmo período, como em 'Ela gosta de ler; ele prefere assistir filmes'.",
"Dica: Utilize a vírgula para separar itens em uma lista, como em 'Comprei arroz, feijão, macarrão e carne'.",
"Dica: Utilize a conjunção 'mas' para contrapor ideias, como em 'Gosto de estudar, mas também gosto de sair com os amigos'.",
"Dica: Utilize a conjunção 'e' para somar ideias, como em 'Ela estuda português e inglês'.",
"Dica: Utilize a conjunção 'ou' para apresentar alternativas, como em 'Você pode escolher entre suco ou refrigerante'.",
"Dica: Evite o uso excessivo de palavras estrangeiras em textos em português. Procure usar o equivalente em português ou, se não houver, explicar o termo em nota de rodapé.",
"Dica: Utilize corretamente os pronomes 'eu' e 'mim'. 'Eu' é usado como sujeito, e 'mim' é usado como objeto.",
"Dica: Evite o uso de redundâncias, como em 'subir para cima' ou 'entrar para dentro'.",
"Dica: Utilize o hífen em palavras compostas, como em 'bem-vindo' ou 'guarda-chuva'.",
"Dica: Utilize a vírgula para separar orações coordenadas, mas não as separe por vírgula se estiverem ligadas por conjunção 'e', 'mas', 'ou', 'nem', 'pois' ou 'porque'.",
"Dica: Utilize a crase antes de palavras femininas que exigem o uso da preposição 'a', como em 'Vou à casa dela'.",
"Dica: Utilize o ponto final para indicar o fim de uma frase declarativa. O ponto de interrogação é usado para perguntas, e o ponto de exclamação para enfatizar uma emoção.",
"Dica: Utilize a concordância verbal e nominal corretamente, prestando atenção à concordância do verbo com o sujeito e à concordância do adjetivo com o substantivo.",
"Dica: Evite o uso de pleonasmos, como em 'subir para cima' ou 'descer para baixo'.",
"Dica: Utilize a pontuação corretamente, prestando atenção à utilização de pontos, vírgulas, ponto e vírgula, dois pontos e travessões.",
"Dica: A concordância verbal é fundamental para uma frase estar correta gramaticalmente. Veja o exemplo: 'As crianças brincam no parque', em que o verbo 'brincam' está no plural para concordar com o sujeito 'crianças'.",
"Dica: O uso adequado da crase é importante para evitar erros comuns. Por exemplo, dizemos 'Vou à praia' (com crase) porque o verbo 'ir' exige a preposição 'a' e o substantivo 'praia' é feminino e singular.",
"Dica: O uso dos pronomes demonstrativos 'este', 'esse' e 'aquele' depende da posição do objeto em relação ao interlocutor. Por exemplo, se o objeto está próximo do falante, utiliza-se 'este'. Se está próximo do ouvinte, utiliza-se 'esse'. E se está distante tanto do falante quanto do ouvinte, utiliza-se 'aquele'.",
"Dica: A regência verbal também é importante para evitar erros. Por exemplo, o verbo 'gostar' pede a preposição 'de', então devemos dizer 'gosto de pizza', e não 'gosto a pizza'.",
"Dica: O uso dos tempos verbais corretos é fundamental para expressar adequadamente as ações no tempo. Por exemplo, o presente do indicativo é utilizado para ações que acontecem no momento da fala, como em 'Eu estudo português', enquanto o pretérito perfeito é utilizado para ações concluídas no passado, como em 'Eu estudei português'.",
"Dica: Ao utilizar siglas ou abreviações, sempre defina seu significado na primeira vez que aparecem no texto e, em seguida, use a sigla ou abreviação. Exemplo: 'O Instituto Nacional de Estudos e Pesquisas Educacionais Anísio Teixeira (INEP) divulgou os resultados do Enem 2022'.",
"Dica: Cuidado com a concordância nominal, verifique sempre se os termos concordam em gênero e número. Exemplo: 'Os livros antigos foram encontrados em bom estado'.",
"Dica: Evite frases ambíguas que possam ser interpretadas de mais de uma maneira. Por exemplo, a frase 'O professor falou para o aluno que ele precisava estudar mais' é ambígua, pois não fica claro se é o professor ou o aluno que precisa estudar mais.",
"Dica: A denotação é o significado literal e objetivo de uma palavra, enquanto a conotação é o significado subjetivo e associativo que ela pode ter.",
"Dica: As palavras podem ter diferentes conotações dependendo do contexto em que são utilizadas, por isso é importante considerar o contexto ao interpretar seu significado.",
"Dica: O uso de figuras de linguagem, como metáforas e ironias, pode alterar o sentido original das palavras, dando-lhes uma conotação diferente do seu significado denotativo.",
"Dica: Para identificar o sujeito de uma frase, pergunte 'quem' realiza a ação do verbo. Por exemplo, na frase 'João comeu a maçã', o sujeito é 'João', pois ele é quem realizou a ação de comer a maçã.",
"Dica: O predicado é tudo o que é dito sobre o sujeito em uma frase. Ele pode ser verbal, nominal ou verbo-nominal. Por exemplo, na frase 'Maria está feliz', o predicado é nominal, pois a palavra 'feliz' atribui uma qualidade ao sujeito 'Maria'.",
"Dica: A análise sintática envolve a identificação das funções sintáticas dos termos que compõem uma frase, como sujeito, predicado, objeto direto e indireto, complemento nominal, entre outros. Essa análise ajuda a entender a estrutura e o significado da frase.",
"Dica: O complemento nominal é um termo que completa o sentido de um nome, geralmente substantivo, e sempre é regido por uma preposição. Exemplo: 'Ela tem amor pela natureza' - 'pela natureza' é o complemento nominal do substantivo 'amor'.",
"Dica: O adjunto adnominal é um termo que modifica ou caracteriza o substantivo, podendo ser representado por adjetivos, locuções adjetivas, pronomes adjetivos, entre outros. Exemplo: 'O carro azul está na garagem' - 'azul' é o adjunto adnominal do substantivo 'carro'.",
"Dica: Para diferenciar o complemento nominal do adjunto adnominal, é preciso analisar a presença ou ausência de preposição. Se houver uma preposição regendo o termo que completa o sentido do substantivo, é complemento nominal. Se não houver preposição e o termo modificar o substantivo, é adjunto adnominal.",
"Dica: Evite o uso excessivo do verbo 'ser' e opte por verbos mais específicos que possam transmitir a ação de maneira mais clara. Exemplo: em vez de 'A casa é grande', utilize 'A casa possui uma grande estrutura'.",
"Dica: Utilize verbos no tempo adequado para transmitir a ação no momento correto. Exemplo: em vez de 'Ontem eu faz a tarefa', utilize 'Ontem eu fiz a tarefa'.",
"Dica: Tenha cuidado ao utilizar verbos transitivos diretos e indiretos, certificando-se de que o objeto esteja na forma correta. Exemplo: em vez de 'Eu enviei o livro para ele', utilize 'Eu enviei-lhe o livro'.",
"Dica: Evite o uso de verbos no gerúndio quando possível, especialmente em situações em que a ação não está em andamento. Exemplo: em vez de 'Estou indo ao cinema', utilize 'Vou ao cinema'.",
"Dica: Cuidado com a regência verbal, que indica a relação que o verbo estabelece com os demais termos da oração. Por exemplo, o verbo 'assistir' pode ser transitivo direto (assistir algo) ou transitivo indireto (assistir a algo). É importante saber qual é a regência do verbo para utilizá-lo corretamente.",
"Dica: Use crase antes de substantivos femininos que exigem a preposição 'a' e que estejam acompanhados de artigo feminino ou pronome feminino. Por exemplo: 'Fui à escola', 'Referi-me àquela pessoa', 'A carta foi entregue à mãe'.",
"Dica: Evite o uso da crase antes de palavras masculinas ou de substantivos no plural. Por exemplo: 'Ele vai à festa', ou 'Ele vai a festas'.",
"Dica: A letra 'S' é utilizada para representar o som de /s/ e pode aparecer no início, meio ou fim das palavras, como em 'sapato', 'passar' e 'mesa'.",
"Dica: O 'SS' é utilizado para representar o som de /s/ duplo e aparece somente no meio das palavras, como em 'passeio', 'assessor' e 'assunto'.",
"Dica: O 'Ç' é utilizado para representar o som de /s/ antes das vogais 'a', 'o' e 'u', e aparece somente antes dessas letras, como em 'aço', 'açougue' e 'açucar'.",
"Dica: Os pronomes pessoais oblíquos átonos são usados para substituir o objeto direto ou indireto na frase. Exemplos: 'Eu vi a Ana ontem' (objeto direto: 'a Ana') pode ser substituído por 'Eu a vi ontem'. Outro exemplo: 'Ele deu o presente para mim' (objeto indireto: 'para mim') pode ser substituído por 'Ele me deu o presente'.",
"Dica: A coerência textual refere-se à conexão lógica entre as ideias apresentadas em um texto, enquanto a coesão textual refere-se à conexão linguística entre as palavras e frases que compõem o texto. Exemplo de coerência: Se um texto fala sobre um tema específico, todas as ideias apresentadas devem estar relacionadas a esse tema de forma lógica e organizada. Exemplo de coesão: Para garantir a coesão, é importante usar conectivos adequados, como 'portanto', 'além disso', 'por outro lado', entre outros, que conectam as frases de forma clara e coesa.",
"Dica: O termo 'porque' é utilizado para explicar ou justificar uma causa ou motivo, como em 'Não fui à festa porque estava doente'.",
"Dica: o termo 'por que' é usado em perguntas diretas e indiretas, representando uma dúvida, como em 'Por que você não veio à festa?' ou 'Não entendi por que você não veio à festa'.",
"Dica: 'Por quê' é utilizado no final de uma frase quando representa uma pergunta, como em 'Você não veio à festa por quê?'.",
"Dica: 'Porque' (junto) é utilizado como conjunção em frases que possuem duas orações, como em 'Não fui à festa porque estava doente e precisava descansar'.",
"Dica: Utilize 'por que' (separado e com espaço) quando houver a junção da preposição 'por' com o pronome interrogativo 'que'. Exemplo: 'Por que você está chorando?",
"Dica: Use 'por quê' (separado, com espaço e acento) quando o pronome interrogativo 'que' estiver no final de uma frase interrogativa. Exemplo: 'Você está chorando por quê?",
"Dica: Empregue 'porque' (junto, sem acento) quando estiver introduzindo uma explicação, causa ou motivo. Exemplo: 'Estou chorando porque me machuquei'.",
"Dica: Já o 'porquê' (junto e com acento) é utilizado como um substantivo, representando o motivo ou a razão. Exemplo: 'Não entendo o porquê de suas atitudes'.",
"Dica: Palavras homônimas são aquelas que possuem a mesma pronúncia, mas têm significados diferentes. É importante estar atento ao contexto para compreender o sentido correto da palavra utilizada. Exemplo de homônimos homófonos: 'cego' (sem visão) e 'sego' (pouco cozido). Exemplo de homônimos homógrafos: 'concerto' (apresentação musical) e 'conserto' (reparo).",
"Dica: Palavras homônimas podem ser classificadas em homônimos perfeitos, que possuem a mesma pronúncia e escrita, e homônimos imperfeitos, que possuem a mesma pronúncia, mas escritas diferentes.",
"Dica: Substantivos: Os substantivos são palavras que nomeiam pessoas, lugares, objetos, sentimentos, entre outros. Eles podem ser classificados em comuns (ex: casa, carro) e próprios (ex: João, Brasil). Fique atento à concordância em gênero (masculino/feminino) e número (singular/plural) dos substantivos.",
"Adjetivos:  Os adjetivos são palavras que atribuem características aos substantivos, expressando qualidades ou estados. Eles concordam em gênero e número com os substantivos que modificam. Observe se o adjetivo é usado antes ou depois do substantivo, pois isso pode alterar o significado. Exemplo: 'O gato preto' (o gato é preto) vs. 'O preto gato' (gato preto por natureza).",
"Dica: Verbos:  Os verbos são palavras que indicam ação, estado ou fenômeno.  Eles se flexionam em tempo (passado, presente, futuro), modo (indicativo, subjuntivo, imperativo) e pessoa (eu, tu, ele/ela, nós, vós, eles/elas).",
"Dica: Advérbios:  Os advérbios modificam o verbo, o adjetivo ou outro advérbio, indicando circunstâncias como tempo, lugar, modo, intensidade, entre outras. Eles podem responder a perguntas como 'quando?', 'onde?', 'como?' e 'quanto?'.",
"Dica: Pronomes: Os pronomes substituem os substantivos, evitando sua repetição na frase. Eles podem ser pessoais (eu, tu, ele/ela), possessivos (meu, teu, dele/dela), demonstrativos (este, esse, aquele), entre outros.",
"Dica: Metáfora: A metáfora é uma figura de linguagem que estabelece uma relação de semelhança entre dois termos, atribuindo características de um ao outro. Exemplo: 'Seu sorriso é um raio de sol'.",
"Dica: Comparação ou símile: A comparação, também conhecida como símile, é uma figura de linguagem que estabelece uma comparação explícita entre dois termos, utilizando conectivos como 'como', 'tal qual', 'parecido com', entre outros. Exemplo: 'Ele corre rápido como um raio'.",
"Dica: Metonímia: A metonímia é uma figura de linguagem que substitui um termo por outro que possui uma relação de proximidade ou associação. Exemplo: 'As mãos no volante' (as mãos representam a pessoa que está dirigindo).",
"Dica: Hipérbole: A hipérbole é uma figura de linguagem que consiste no exagero intencional de uma ideia, aumentando ou diminuindo sua intensidade. Exemplo: 'Estou morrendo de fome!'",
"Dica: Ironia: A ironia é uma figura de linguagem que expressa o contrário do que se pretende dizer, de forma sarcástica ou humorística. Exemplo: 'Que dia maravilhoso... só choveu o dia inteiro!",
"Dica: Personificação: A personificação é uma figura de linguagem que atribui características humanas a objetos inanimados ou seres não humanos. Exemplo: 'A lua sorriu para mim.'",
"Dica: Variação de estilo: Sinônimos podem ajudar a evitar repetições excessivas e a enriquecer seu texto. Experimente usar sinônimos para substituir palavras repetitivas ou para variar o estilo de escrita.",
"Dica: Posição do adjetivo: Normalmente, os adjetivos são colocados antes do substantivo, mas também podem aparecer depois em alguns casos. Exemplo: 'Uma casa pequena' / 'Um livro interessante.'",
"Dica: Grau do adjetivo: Os adjetivos podem expressar diferentes graus de comparação, como positivo, comparativo e superlativo. Por exemplo, 'bonito' (positivo), 'mais bonito' (comparativo) e 'o mais bonito' (superlativo).",
"Dica: Os adjetivos descrevem características como cor, tamanho, forma, qualidade, estado, nacionalidade, idade, entre outros. Por exemplo, em 'uma casa grande', o adjetivo 'grande' descreve o tamanho da casa.",
"Dica: Hiato: O hiato ocorre quando duas vogais estão juntas em uma palavra, mas são pronunciadas separadamente em sílabas diferentes. Exemplo: 'sa-ú-de', 'ba-ú', 'ru-í-do'.",
"Dica: Ditongo: O ditongo ocorre quando duas vogais estão juntas em uma palavra e são pronunciadas na mesma sílaba. Pode ser um ditongo crescente, quando a vogal mais fraca vem antes da mais forte, ou um ditongo decrescente, quando a vogal mais fraca vem depois da mais forte. Exemplo de ditongo crescente: 'pai', 'ceu', 'fei-to'. Exemplo de ditongo decrescente: 'po-e-ta', 'ai-re', 'ru-im'.",
"Dica: Tritongo: O tritongo ocorre quando três vogais estão juntas em uma palavra e são pronunciadas na mesma sílaba. É importante lembrar que, ao separar uma palavra em sílabas, o tritongo é mantido na mesma sílaba. Exemplo: 'pa-ra-guai' - Perceba que as três vogais u a e i estão juntas na mesma sílaba.",
"Dica: Separação de sílabas: No hiato, as vogais são separadas em sílabas diferentes. No ditongo e no tritongo, as vogais estão na mesma sílaba. É importante conhecer as regras de separação de sílabas para identificar corretamente o hiato, ditongo ou tritongo em uma palavra.",

];

function gerarDica() {
	const indiceAleatorio = Math.floor(Math.random() * dicas.length);
	const dica = dicas[indiceAleatorio];
	document.getElementById("dica").innerHTML = dica;
}

gerarDica();
