const dicas = [
"Dica: Evite usar gírias em textos formais.",
"Dica: Sempre utilize a vírgula antes da conjunção 'e' quando há mais de dois elementos.",
"Dica: Use 'a' antes de palavras femininas e 'o' antes de palavras masculinas.",	"Dica: O correto é 'mais' quando se refere a quantidade e 'mas' quando se opõe a algo.",
"Dica: Sempre coloque acento no 'é' (verbo ser) e no 'é' (verbo estar) para diferenciar ações permanentes de ações momentâneas.",
"Dica: Use o hífen para unir as palavras compostas (como 'pé-de-moleque', 'guarda-chuva', etc).",
"Dica: Evite usar palavras vulgares ou de baixo calão em textos formais.",
"Dica: Utilize a crase antes de substantivos femininos que indicam lugar (como 'à escola', 'à igreja', etc).",
"Dica: Utilize o ponto final para encerrar frases declarativas e o ponto de interrogação para fazer perguntas.",
"Dica: Utilize a vírgula para separar elementos em uma enumeração, mas nunca antes da conjunção 'e'.",
"Dica: Evite o uso excessivo de pronomes em uma frase, especialmente quando eles se referem a objetos ou coisas inanimadas.",
"Dica: Utilize o ponto e vírgula para separar frases independentes que estejam relacionadas entre si.",
"Dica: Utilize a linguagem coloquial apenas em contextos informais e evite seu uso em textos formais.",
"Dica: Utilize acentos diferenciais em palavras como 'pôr' e 'pôde' para diferenciá-las de outras palavras homófonas.", 
"Dica: Evite o uso de palavras repetitivas em um mesmo parágrafo, para não tornar o texto monótono e cansativo.",
"Dica: Utilize o ponto de exclamação com moderação, pois seu uso excessivo pode tornar o texto pouco crível e exagerado.",
"Dica: Utilize corretamente os pronomes relativos 'que' e 'quem', para não comprometer a clareza e a compreensão da frase.",
"Dica: Utilize o apóstrofo para indicar a supressão de letras em palavras contraídas, como em 'd'água' e 'não sei'.",
"Dica: Evite o uso de termos técnicos ou jargões em textos destinados a um público geral, a menos que estejam bem explicados no contexto.", 
"Dica: Utilize o acento agudo nas vogais tônicas 'a', 'e' e 'o' das palavras oxítonas, como em 'café', 'bebê' e 'avô'",
"Dica: Utilize o acento circunflexo nas vogais tônicas 'a', 'e' e 'o' das palavras paroxítonas, como em 'pêssego', 'carência' e 'cômodo'",
"Dica: Utilize o acento grave para indicar a crase, que é a contração da preposição 'a' com o artigo feminino 'a', como em 'à casa' e 'à escola'",
"Dica: Utilize o trema para indicar a pronúncia correta de vogais que formam um hiato, como em 'linguiça'",
"Dica: Utilize o acento diferencial em palavras homógrafas para diferenciá-las, como em 'pôde' (pretérito perfeito do verbo poder) e 'pode' (presente do indicativo do verbo poder)'",
"Dica: Utilize 'onde' quando se refere a lugar físico e 'em que' quando se refere a lugar abstrato.",
"Dica: As palavras proparoxítonas sempre são acentuadas, como em 'sábado', 'próximo' e 'próton'.",
"Dica: As palavras terminadas em ditongo crescente (ou seja, quando a vogal mais fraca vem primeiro) são acentuadas, como em 'saúde', 'chapéu' e 'herói'.",
"Dica: As palavras terminadas em 'em', 'ens' e 'on' são acentuadas na sílaba tônica, como em 'parabéns', 'hífen' e 'órgão'.",
"Dica: As palavras terminadas em 'ã', 'ãs', 'ão' e 'ões' são acentuadas, como em 'amanhã', 'irmãs', 'coração' e 'nações'.",
"Dica: Utilize sempre letras maiúsculas no início de frases, nomes próprios e em siglas, como em 'Brasil', 'UNESCO' e 'João'.",
"Dica: O uso da crase é obrigatório antes de palavras femininas que exigem a preposição 'a' e que podem ser substituídas por 'àquela', como em 'fui à escola', 'à espera de um milagre' e 'à moda antiga'.",
"Dica: O uso do hífen é obrigatório em palavras compostas com prefixos 'ex', 'vice', 'pró', 'pós' e 'pré', como em 'ex-presidente', 'vice-diretor', 'pró-reitor', 'pós-graduação' e 'pré-história'.",
"Dica: Utilize o ponto final para marcar o final de uma frase declarativa, o ponto de exclamação para marcar uma emoção intensa e o ponto de interrogação para marcar uma pergunta.",
"Dica: Ao utilizar siglas, escreva todas as letras em maiúsculo, como em 'ONG', 'ABNT' e 'IBGE'.",
"Dica: Utilize o ponto de exclamação para finalizar frases declarativas e imperativas, como em 'Faça sua inscrição agora!'.",
"Dica: Utilize o ponto de interrogação para indicar perguntas diretas, como em 'Qual é o seu nome?' e 'Você já fez a tarefa?'.",
"Dica: Utilize o ponto e vírgula para separar ideias independentes dentro de um mesmo período, como em 'Ela gosta de ler; ele prefere assistir filmes'.",
"Dica: Utilize a vírgula para separar itens em uma lista, como em 'Comprei arroz, feijão, macarrão e carne'.",
"Dica: Utilize a conjunção 'mas' para contrapor ideias, como em 'Gosto de estudar, mas também gosto de sair com os amigos'.",
"Dica: Utilize a conjunção 'e' para somar ideias, como em 'Ela estuda português e inglês'.",
"Dica: Utilize a conjunção 'ou' para apresentar alternativas, como em 'Você pode escolher entre suco ou refrigerante'.",
"Dica: Evite o uso excessivo de palavras estrangeiras em textos em português. Procure usar o equivalente em português ou, se não houver, explicar o termo em nota de rodapé.",
"Dica: Utilize corretamente os pronomes 'eu' e 'mim'. 'Eu' é usado como sujeito, e 'mim' é usado como objeto.",
"Dica: Evite o uso de redundâncias, como em 'subir para cima' ou 'entrar para dentro'.",
"Dica: Utilize o hífen em palavras compostas, como em 'bem-vindo' ou 'guarda-chuva'.",
"Dica: Utilize a vírgula para separar orações coordenadas, mas não as separe por vírgula se estiverem ligadas por conjunção 'e', 'mas', 'ou', 'nem', 'pois' ou 'porque'.",
"Dica: Utilize a crase antes de palavras femininas que exigem o uso da preposição 'a', como em 'Vou à casa dela'.",
"Dica: Utilize o ponto final para indicar o fim de uma frase declarativa. O ponto de interrogação é usado para perguntas, e o ponto de exclamação para enfatizar uma emoção.",
"Dica: Utilize a concordância verbal e nominal corretamente, prestando atenção à concordância do verbo com o sujeito e à concordância do adjetivo com o substantivo.",
"Dica: Evite o uso de pleonasmos, como em 'subir para cima' ou 'descer para baixo'.",
"Dica: Utilize a pontuação corretamente, prestando atenção à utilização de pontos, vírgulas, ponto e vírgula, dois pontos e travessões.",
"Dica: A concordância verbal é fundamental para uma frase estar correta gramaticalmente. Veja o exemplo: 'As crianças brincam no parque', em que o verbo 'brincam' está no plural para concordar com o sujeito 'crianças'.",
"Dica: O uso adequado da crase é importante para evitar erros comuns. Por exemplo, dizemos 'Vou à praia' (com crase) porque o verbo 'ir' exige a preposição 'a' e o substantivo 'praia' é feminino e singular.",
"Dica: O uso dos pronomes demonstrativos 'este', 'esse' e 'aquele' depende da posição do objeto em relação ao interlocutor. Por exemplo, se o objeto está próximo do falante, utiliza-se 'este'. Se está próximo do ouvinte, utiliza-se 'esse'. E se está distante tanto do falante quanto do ouvinte, utiliza-se 'aquele'.",
"Dica: A regência verbal também é importante para evitar erros. Por exemplo, o verbo 'gostar' pede a preposição 'de', então devemos dizer 'gosto de pizza', e não 'gosto a pizza'.",
"Dica: O uso dos tempos verbais corretos é fundamental para expressar adequadamente as ações no tempo. Por exemplo, o presente do indicativo é utilizado para ações que acontecem no momento da fala, como em 'Eu estudo português', enquanto o pretérito perfeito é utilizado para ações concluídas no passado, como em 'Eu estudei português'.",
"Dica: Ao utilizar siglas ou abreviações, sempre defina seu significado na primeira vez que aparecem no texto e, em seguida, use a sigla ou abreviação. Exemplo: 'O Instituto Nacional de Estudos e Pesquisas Educacionais Anísio Teixeira (INEP) divulgou os resultados do Enem 2022'.",
"Dica: Cuidado com a concordância nominal, verifique sempre se os termos concordam em gênero e número. Exemplo: 'Os livros antigos foram encontrados em bom estado'.",
"Dica: Evite frases ambíguas que possam ser interpretadas de mais de uma maneira. Por exemplo, a frase 'O professor falou para o aluno que ele precisava estudar mais' é ambígua, pois não fica claro se é o professor ou o aluno que precisa estudar mais.",
"Dica: A denotação é o significado literal e objetivo de uma palavra, enquanto a conotação é o significado subjetivo e associativo que ela pode ter.",
"Dica: As palavras podem ter diferentes conotações dependendo do contexto em que são utilizadas, por isso é importante considerar o contexto ao interpretar seu significado.",
"Dica: O uso de figuras de linguagem, como metáforas e ironias, pode alterar o sentido original das palavras, dando-lhes uma conotação diferente do seu significado denotativo.",
"Dica: Para identificar o sujeito de uma frase, pergunte 'quem' realiza a ação do verbo. Por exemplo, na frase 'João comeu a maçã', o sujeito é 'João', pois ele é quem realizou a ação de comer a maçã.",
"Dica: O predicado é tudo o que é dito sobre o sujeito em uma frase. Ele pode ser verbal, nominal ou verbo-nominal. Por exemplo, na frase 'Maria está feliz', o predicado é nominal, pois a palavra 'feliz' atribui uma qualidade ao sujeito 'Maria'.",
"Dica: A análise sintática envolve a identificação das funções sintáticas dos termos que compõem uma frase, como sujeito, predicado, objeto direto e indireto, complemento nominal, entre outros. Essa análise ajuda a entender a estrutura e o significado da frase.",
"Dica: O complemento nominal é um termo que completa o sentido de um nome, geralmente substantivo, e sempre é regido por uma preposição. Exemplo: 'Ela tem amor pela natureza' - 'pela natureza' é o complemento nominal do substantivo 'amor'.",
"Dica: O adjunto adnominal é um termo que modifica ou caracteriza o substantivo, podendo ser representado por adjetivos, locuções adjetivas, pronomes adjetivos, entre outros. Exemplo: 'O carro azul está na garagem' - 'azul' é o adjunto adnominal do substantivo 'carro'.",
"Dica: Para diferenciar o complemento nominal do adjunto adnominal, é preciso analisar a presença ou ausência de preposição. Se houver uma preposição regendo o termo que completa o sentido do substantivo, é complemento nominal. Se não houver preposição e o termo modificar o substantivo, é adjunto adnominal.",
"Dica: Evite o uso excessivo do verbo 'ser' e opte por verbos mais específicos que possam transmitir a ação de maneira mais clara. Exemplo: em vez de 'A casa é grande', utilize 'A casa possui uma grande estrutura'.",
"Dica: Utilize verbos no tempo adequado para transmitir a ação no momento correto. Exemplo: em vez de 'Ontem eu faz a tarefa', utilize 'Ontem eu fiz a tarefa'.",
"Dica: Tenha cuidado ao utilizar verbos transitivos diretos e indiretos, certificando-se de que o objeto esteja na forma correta. Exemplo: em vez de 'Eu enviei o livro para ele', utilize 'Eu enviei-lhe o livro'.",
"Dica: Evite o uso de verbos no gerúndio quando possível, especialmente em situações em que a ação não está em andamento. Exemplo: em vez de 'Estou indo ao cinema', utilize 'Vou ao cinema'.",
"Dica: Cuidado com a regência verbal, que indica a relação que o verbo estabelece com os demais termos da oração. Por exemplo, o verbo 'assistir' pode ser transitivo direto (assistir algo) ou transitivo indireto (assistir a algo). É importante saber qual é a regência do verbo para utilizá-lo corretamente.",
"Dica: Use crase antes de substantivos femininos que exigem a preposição 'a' e que estejam acompanhados de artigo feminino ou pronome feminino. Por exemplo: 'Fui à escola', 'Referi-me àquela pessoa', 'A carta foi entregue à mãe'.",
"Dica: Evite o uso da crase antes de palavras masculinas ou de substantivos no plural. Por exemplo: 'Ele vai à festa', ou 'Ele vai a festas'.",
"Dica: A letra 'S' é utilizada para representar o som de /s/ e pode aparecer no início, meio ou fim das palavras, como em 'sapato', 'passar' e 'mesa'.",
"Dica: O 'SS' é utilizado para representar o som de /s/ duplo e aparece somente no meio das palavras, como em 'passeio', 'assessor' e 'assunto'.",
"Dica: O 'Ç' é utilizado para representar o som de /s/ antes das vogais 'a', 'o' e 'u', e aparece somente antes dessas letras, como em 'aço', 'açougue' e 'açucar'.",
"Dica: Os pronomes pessoais oblíquos átonos são usados para substituir o objeto direto ou indireto na frase. Exemplos: 'Eu vi a Ana ontem' (objeto direto: 'a Ana') pode ser substituído por 'Eu a vi ontem'. Outro exemplo: 'Ele deu o presente para mim' (objeto indireto: 'para mim') pode ser substituído por 'Ele me deu o presente'.",
"Dica: A coerência textual refere-se à conexão lógica entre as ideias apresentadas em um texto, enquanto a coesão textual refere-se à conexão linguística entre as palavras e frases que compõem o texto. Exemplo de coerência: Se um texto fala sobre um tema específico, todas as ideias apresentadas devem estar relacionadas a esse tema de forma lógica e organizada. Exemplo de coesão: Para garantir a coesão, é importante usar conectivos adequados, como 'portanto', 'além disso', 'por outro lado', entre outros, que conectam as frases de forma clara e coesa.",
"Dica: O termo 'porque' é utilizado para explicar ou justificar uma causa ou motivo, como em 'Não fui à festa porque estava doente'.",
"Dica: o termo 'por que' é usado em perguntas diretas e indiretas, representando uma dúvida, como em 'Por que você não veio à festa?' ou 'Não entendi por que você não veio à festa'.",
"Dica: 'Por quê' é utilizado no final de uma frase quando representa uma pergunta, como em 'Você não veio à festa por quê?'.",
"Dica: 'Porque' (junto) é utilizado como conjunção em frases que possuem duas orações, como em 'Não fui à festa porque estava doente e precisava descansar'.",

];

function gerarDica() {
	const indiceAleatorio = Math.floor(Math.random() * dicas.length);
	const dica = dicas[indiceAleatorio];
	document.getElementById("dica").innerHTML = dica;
}

gerarDica();
